#!/usr/bin/env node
// Turns the Turath 2026 site (the rest of this repo) into the app's www/.
//
// The site is static and already uses relative links, so it runs from the app bundle almost as is.
// Three things do not, and this script fixes them at build time rather than touching the site:
//   1. Directory links ("./library/", "../../"). Capacitor serves any extensionless path as the
//      root index.html (SPA routing), so every such link would land on the home page. They are
//      rewritten to ".../index.html"; app/shim.js does the same for links the site's JS builds.
//   2. Google Fonts. Replaced by the same families bundled from @fontsource, so the app reads
//      offline with the site's real typography.
//   3. PDFs (~20 MB). Left out of the bundle and linked to the live site, which the OS opens in
//      the browser or its PDF viewer.
//
// Source: the site at the root of this repo (mobile/ lives beside it), or $TURATH_SRC if set.
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const OUT = path.join(HERE, 'www');
const LIVE = 'https://ahmedhaz.github.io/turath-2026/';
const SKIP = new Set(['.git', '.github', '.nojekyll', '_headers', 'README.md', 'CNAME', 'mobile', 'node_modules']);
const SITE = process.env.TURATH_SRC ? path.resolve(process.env.TURATH_SRC) : path.dirname(HERE);

function walk(dir, rel = '') {
  const out = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (!rel && SKIP.has(e.name)) continue;
    const r = rel ? rel + '/' + e.name : e.name;
    if (e.isDirectory()) out.push(...walk(path.join(dir, e.name), r));
    else out.push(r);
  }
  return out;
}

// "../../" for a page two folders deep, "./" at the root.
const rootOf = (rel) => '../'.repeat(rel.split('/').length - 1) || './';

function fixUrl(url, rel) {
  if (/^([a-z][a-z0-9+.-]*:|#|\/\/)/i.test(url) || url === '') return url;
  const i = url.search(/[?#]/);
  let p = i < 0 ? url : url.slice(0, i);
  const tail = i < 0 ? '' : url.slice(i);
  if (/\.pdf$/i.test(p)) {
    const abs = path.posix.normalize(path.posix.join(path.posix.dirname(rel), p));
    return LIVE + abs + tail;
  }
  if (p === '' ) return url;
  if (p === '.' || p === '..' || p.endsWith('/')) p = (p.endsWith('/') ? p : p + '/') + 'index.html';
  return p + tail;
}

const FONT_LINKS = /<link rel="preconnect" href="https:\/\/fonts\.googleapis\.com">\s*<link rel="preconnect" href="https:\/\/fonts\.gstatic\.com" crossorigin>\s*<link rel="stylesheet" href="https:\/\/fonts\.googleapis\.com\/css2[^"]*">/;

function page(html, rel) {
  const root = rootOf(rel);
  if (!FONT_LINKS.test(html)) throw new Error(`${rel}: Google Fonts links not found; update FONT_LINKS`);
  html = html.replace(FONT_LINKS, `<link rel="stylesheet" href="${root}fonts/fonts.css">`);
  html = html.replace(/\b(href|src)="([^"]*)"/g, (_, a, u) => `${a}="${fixUrl(u, rel)}"`);
  html = html.replace('</head>', `<script src="${root}app/shim.js"></script>\n</head>`);
  return html;
}

// The families and weights the site asks Google Fonts for, from @fontsource, woff2 only.
const FONTS = {
  amiri: ['400', '700', '400-italic'],
  'noto-naskh-arabic': ['400', '500', '600', '700'],
  'ibm-plex-sans-arabic': ['400', '500', '600'],
  newsreader: ['400', '600'],
};
const SUBSETS = ['arabic', 'latin', 'latin-ext'];

function fonts() {
  const dir = path.join(OUT, 'fonts');
  fs.mkdirSync(dir, { recursive: true });
  let css = '/* Generated by scripts/build-www.mjs from @fontsource; OFL-licensed fonts. */\n';
  for (const [fam, weights] of Object.entries(FONTS)) {
    const pkg = path.join(HERE, 'node_modules/@fontsource', fam);
    fs.mkdirSync(path.join(dir, fam), { recursive: true });
    fs.copyFileSync(path.join(pkg, 'LICENSE'), path.join(dir, fam, 'LICENSE'));
    for (const w of weights) {
      for (const s of SUBSETS) {
        const f = path.join(pkg, `${s}-${w}.css`);
        if (!fs.existsSync(f)) continue;
        css += fs.readFileSync(f, 'utf8').replace(/src: url\(\.\/files\/([^)]+\.woff2)\) format\('woff2'\)[^;]*;/g, (_, file) => {
          fs.copyFileSync(path.join(pkg, 'files', file), path.join(dir, fam, file));
          return `src: url(./${fam}/${file}) format('woff2');`;
        });
      }
    }
  }
  fs.writeFileSync(path.join(dir, 'fonts.css'), css);
}

const src = SITE;
fs.rmSync(OUT, { recursive: true, force: true });
let pages = 0, skipped = 0;
for (const rel of walk(src)) {
  if (/\.pdf$/i.test(rel)) { skipped++; continue; }
  const to = path.join(OUT, rel);
  fs.mkdirSync(path.dirname(to), { recursive: true });
  if (rel.endsWith('.html')) {
    fs.writeFileSync(to, page(fs.readFileSync(path.join(src, rel), 'utf8'), rel));
    pages++;
  } else {
    fs.copyFileSync(path.join(src, rel), to);
  }
}
fs.mkdirSync(path.join(OUT, 'app'), { recursive: true });
fs.copyFileSync(path.join(HERE, 'app/shim.js'), path.join(OUT, 'app/shim.js'));
fonts();
const rev = (() => { try { return execFileSync('git', ['-C', src, 'rev-parse', '--short', 'HEAD']).toString().trim() } catch { return 'unknown' } })();
fs.writeFileSync(path.join(OUT, 'app/build.json'), JSON.stringify({ rev, built: new Date().toISOString() }) + '\n');
console.log(`www/: ${pages} pages from ${rev}, ${skipped} PDFs linked to ${LIVE}`);
